language: android
install: true

os: linux
dist: trusty
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30
    - add-on
    - extra

before_script:
  - yes | /usr/local/android-sdk/tools/bin/sdkmanager "build-tools;30.0.2"
  - yes | /usr/local/android-sdk/tools/bin/sdkmanager "platforms;android-30"

jobs:
  include:
    - stage: build
      script: ./gradlew build -s -x jvmTest -x jsIrTest -x jsIrBrowserTest -x jsIrNodeTest -x jsLegacyTest -x jsLegacyBrowserTest -x jsLegacyNodeTest
#    Tests are temporarily disabled on public travis due to the problems of launching
#    - state: test
#      script: ./gradlew allTests
